version: '3.8'

services:

  app:
    image: bassbeaver/eventhouse:latest
    container_name: eventhouse-app
    volumes:
      - ../src:/app/src
      - ../load-testing:/app/load-testing
      - ../docker:/app/docker
      - ./images/app/scripts:/scripts
      - ./volumes/gopath/pkg:/go/pkg # Local go mod cache
      - ./volumes/logs/app:/app/logs
    env_file:
      - app.env
    depends_on:
      - clickhouse
    networks:
      eventhouse:
        ipv4_address: 192.168.66.10
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined

  clickhouse:
    image: yandex/clickhouse-server:21.5-alpine
    container_name: eventhouse-clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./images/clickhouse/init.sh:/docker-entrypoint-initdb.d/init-db.sh
      - clickhouse-data:/var/lib/clickhouse
    networks:
      eventhouse:
        ipv4_address: 192.168.66.20

  provision:
    build:
      context: .
      dockerfile: ./images/provision/Dockerfile
    image: bassbeaver/eventhouse-provision:latest
    container_name: eventhouse-provision
    volumes:
      - ../.:/app
      - ./volumes/gopath/pkg:/go/pkg

volumes:
  clickhouse-data: {}

networks:
  eventhouse:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.66.0/24