<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Eventhouse\Grpc\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eventhouse.grpc.event.EntityStreamRequest</code>
 */
class EntityStreamRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string entityType = 1;</code>
     */
    protected $entityType = '';
    /**
     * Generated from protobuf field <code>string entityId = 2;</code>
     */
    protected $entityId = '';
    /**
     * Generated from protobuf field <code>.eventhouse.grpc.event.EntityStreamRequest.Filter filter = 3;</code>
     */
    protected $filter = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $entityType
     *     @type string $entityId
     *     @type \Eventhouse\Grpc\Event\EntityStreamRequest\Filter $filter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string entityType = 1;</code>
     * @return string
     */
    public function getEntityType()
    {
        return $this->entityType;
    }

    /**
     * Generated from protobuf field <code>string entityType = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityType($var)
    {
        GPBUtil::checkString($var, True);
        $this->entityType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string entityId = 2;</code>
     * @return string
     */
    public function getEntityId()
    {
        return $this->entityId;
    }

    /**
     * Generated from protobuf field <code>string entityId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->entityId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eventhouse.grpc.event.EntityStreamRequest.Filter filter = 3;</code>
     * @return \Eventhouse\Grpc\Event\EntityStreamRequest\Filter|null
     */
    public function getFilter()
    {
        return isset($this->filter) ? $this->filter : null;
    }

    public function hasFilter()
    {
        return isset($this->filter);
    }

    public function clearFilter()
    {
        unset($this->filter);
    }

    /**
     * Generated from protobuf field <code>.eventhouse.grpc.event.EntityStreamRequest.Filter filter = 3;</code>
     * @param \Eventhouse\Grpc\Event\EntityStreamRequest\Filter $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkMessage($var, \Eventhouse\Grpc\Event\EntityStreamRequest\Filter::class);
        $this->filter = $var;

        return $this;
    }

}

