<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Eventhouse\Grpc\Event;

if (false) {
    /**
     * This class is deprecated. Use Eventhouse\Grpc\Event\EntityStreamRequest\Filter instead.
     * @deprecated
     */
    class EntityStreamRequest_Filter {}
}
class_exists(EntityStreamRequest\Filter::class);
@trigger_error('Eventhouse\Grpc\Event\EntityStreamRequest_Filter is deprecated and will be removed in the next major release. Use Eventhouse\Grpc\Event\EntityStreamRequest\Filter instead', E_USER_DEPRECATED);

