<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Eventhouse\Grpc\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eventhouse.grpc.event.GlobalStreamRequest</code>
 */
class GlobalStreamRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string eventIdFrom = 1;</code>
     */
    protected $eventIdFrom = '';
    /**
     * Generated from protobuf field <code>repeated string entityType = 2;</code>
     */
    private $entityType;
    /**
     * Generated from protobuf field <code>repeated string eventType = 3;</code>
     */
    private $eventType;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $eventIdFrom
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $entityType
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $eventType
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string eventIdFrom = 1;</code>
     * @return string
     */
    public function getEventIdFrom()
    {
        return $this->eventIdFrom;
    }

    /**
     * Generated from protobuf field <code>string eventIdFrom = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEventIdFrom($var)
    {
        GPBUtil::checkString($var, True);
        $this->eventIdFrom = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string entityType = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEntityType()
    {
        return $this->entityType;
    }

    /**
     * Generated from protobuf field <code>repeated string entityType = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEntityType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->entityType = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string eventType = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEventType()
    {
        return $this->eventType;
    }

    /**
     * Generated from protobuf field <code>repeated string eventType = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEventType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->eventType = $arr;

        return $this;
    }

}

