<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Eventhouse\Grpc\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eventhouse.grpc.event.PushRequest</code>
 */
class PushRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string idempotencyKey = 1;</code>
     */
    protected $idempotencyKey = '';
    /**
     * Generated from protobuf field <code>string eventType = 2;</code>
     */
    protected $eventType = '';
    /**
     * Generated from protobuf field <code>string entityType = 3;</code>
     */
    protected $entityType = '';
    /**
     * Generated from protobuf field <code>string entityId = 4;</code>
     */
    protected $entityId = '';
    /**
     * Generated from protobuf field <code>string payload = 5;</code>
     */
    protected $payload = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $idempotencyKey
     *     @type string $eventType
     *     @type string $entityType
     *     @type string $entityId
     *     @type string $payload
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string idempotencyKey = 1;</code>
     * @return string
     */
    public function getIdempotencyKey()
    {
        return $this->idempotencyKey;
    }

    /**
     * Generated from protobuf field <code>string idempotencyKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->idempotencyKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string eventType = 2;</code>
     * @return string
     */
    public function getEventType()
    {
        return $this->eventType;
    }

    /**
     * Generated from protobuf field <code>string eventType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEventType($var)
    {
        GPBUtil::checkString($var, True);
        $this->eventType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string entityType = 3;</code>
     * @return string
     */
    public function getEntityType()
    {
        return $this->entityType;
    }

    /**
     * Generated from protobuf field <code>string entityType = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityType($var)
    {
        GPBUtil::checkString($var, True);
        $this->entityType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string entityId = 4;</code>
     * @return string
     */
    public function getEntityId()
    {
        return $this->entityId;
    }

    /**
     * Generated from protobuf field <code>string entityId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->entityId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payload = 5;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>string payload = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, True);
        $this->payload = $var;

        return $this;
    }

}

